owner: jeancloude
repo: status

sites:
  - name: Accueil
    url: https://jeancloude.club
  - name: VIP
    url: https://vip.jeancloude.club

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: STATUS.JEANCLOUDE.CLUB
  navbar:
    - title: Status
      href: /

assignees:
  - trivoallan
