owner: jeancloude-club
repo: status

sites:
  - name: VIP
    url: https://vip.jeancloude.club

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: STATUS.JEANCLOUDE.CLUB
  navbar:
    - title: Status
      href: /

assignees: # Users to assign downtime issues (optional)
  - trivoallan