owner: jeancloude
repo: status

sites:
  - name: cartemembre
    url: https://cartemembre.jeancloude.club
  - name: home
    url: https://jeancloude.club
  - name: teloche
    url: https://teloche.jeancloude.club
  - name: vip
    url: https://vip.jeancloude.club

status-website:
  cname: status.jeancloude.club
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status . jeancloude . club
  navbar:
    - title: jeancloude . club 
      href: https://jeancloude.club

assignees:
  - trivoallan
